language: node_js

node_js:
  - 'lts/dubnium'

sudo: required

services:
  - docker

before_install:
  - npm install --global npm

install:
  - npm install --no-optional

script:
  - NODE_ENV=production npm run build
  - npm test

deploy:
  provider: npm
  email: contact@cichol.com
  api_key:
    secure: gWpqbnKTl+uoXSHMNY6fc80AJ8fd8ARVs4DqL6Ffmhsivbu4ZEwMrKOdySEoojqgPpexkZ0PQEXrVs76EAgUo7xzshvBTqsmBJ5CAQTQwetnQORp2iqOzcISV76WrGAgaj/6UItSEsqW6t9WxuG3ywUGSKFvrQ/bDrYEmaNXVHTUhFvWkhyyjId2ZrftWtCpAvVVpPPewles7H+7qBuN0W/fubxkAUV1kbsF3jUh4zzM9Y2B8fAJ4uQM8atBdbt2f/zyUQSd/NNIGToG0fYDXDv+z1Zt13Uj2FT0LHFSURUOo8JNIJLN09UnUFzy9EkpoqfOJRqWenMJRGjRncHiwpVxjl3b00Qan6DeipBxq+pIDt4CBTkkxax74pUGhxIheAouXOUUB0so1yXNUbAsDnIgnHxTAXfS2hoZ5nWUVD6RhkFqbnfQOtHOy9OIJPZGFONlN8cU5DkDEAYTO0x7AaJsQ25ok2jktuC+xwHocLi6rv9cvBahoQSsqv/UYMOaQgeke2Fex/TEuXnkp1BnM1ISItZsPwziArmMfn4Ov/0L7iVeAPZlPZhCcNEpifBNUBjhtxSEX4BKBp3Q/Agm86ObgTzWeKk/wdQ+m3hXCRsX6vxB9kW6SHSiZIpYtR20tXX4J1x4Q9uOR8VAqZVRXNw0EHiFAbH+bP+2E2HW6VE=
  on:
    tags: true
    repo: epicinium/clavem
    branch: master
  skip_cleanup: true
